### ISSUE TITLE
close the MET receipe

### ISSUE THREAD

**Issue by TaiSakuma** [cms-met/cmssw#1]
(As we discussed in emails, we are going to use here the github Issues to manage tasks.  This is the first entry. We need to develop our method of tracking the progress in the tasks.)

After checking out the official CMSSW release, users need to check out extra code in order to use the most up-to-date code for MET. We have been providing such code as MET recipes. The MET recipes have been quite actively provided and widely used in CMSSW_5_3.  The recipes for CMSSW_5_3 have been provided on the twiki:
-  https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe53X

The recipe was also provided for the last version of CMSSW_5_2, i.e., CMSSW_5_2_9:
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe52X

There was a plan to provide it for CMSSW_6_2
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe62X

In addition to the above three twiki about particular CMSSW releases, there is an entry page that has links to the three twikis:
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe

In addition to the MET recipe, users typically need to check out the PAT recipes, which are also provided for each CMSSW release
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATReleaseNotes72X
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATReleaseNotes70X
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATReleaseNotes52X (include 53X)

The entry twiki for the PAT recipes is
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuidePATRecipes

There has been an idea for a long time that we should combine the PAT recipe and MET recipe in order to simplify the checkout process of the users.

On the other hand, _Analysis releases_ have been introduced in the official CMSSW, in which the official CMSSW releases accept new code for analysis even after they are closed for new code for the production  [Indico (Feb 17)](https://indico.cern.ch/event/302415/contribution/8), [Indico (Jul 3)](https://indico.cern.ch/event/327563/contribution/14), [Indico (Jul 23)](https://indico.cern.ch/event/332108/contribution/1). The code in the MET recipe is for analysis; therefore, it can be potentially integrated in the official CMSSW releases that are already being used for the central production.

We need to 
- [ ] investigate exactly how analysis releases work

Then,
- [x] integrate the current MET recipes for CMSSW_5_3 into the official CMSSW release if we can, otherwise, into the PAT recipe
- [x] update the twiki https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe53X

We will also need to
- [x] update the following twikis, describing there will be no more MET recipes and explaining where the up-to-date code is integrated
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMetAnalysis

**Comment by mariadalfonso** [comment]
We can split the work in this way
1) Tai: prepare a tag with all the 53X things to add to som CMSSW analysis releases
2) Matthieu will take care of the 7X it's all ongoing and we already know that we need to add things to the analysis releases to make people running on the miniAOD.
3) Maria/Robert can update all the twikis once things are done so that at least I know what is going on.

**Comment by TaiSakuma** [comment]
Perhaps, we cannot entirely close the MET recipe. 

These are a recipe for 7_2_3 

```
git-cms-merge-topic -u cms-met:72X-mvaMETForMiniAOD
git-cms-merge-topic -u cms-met:72X-METSignificance
```

Even if these branches will be soon merged to the official CMSSW, until then, users will need to checkout these from github.

**Comment by TaiSakuma** [comment]
I looked at the files modified in the branches `cms-met:72X-mvaMETForMiniAOD` and `cms-met:72X-METSignificance`.

Neither of them can be in the official CMSSW_7_2_X as they are.

They change the code in RECO. `cms-met:72X-mvaMETForMiniAOD` even changes the data format.

If the code to build MVA MET and MET significance from MiniAOD to be in the official CMSSW_7_2_X, it needs to be implemented in Analysis Tools.

**Comment by TaiSakuma** [comment]
This is done. The MET recipe for 5_3_X is merged in CMSSW_5_3_24
- https://github.com/cms-sw/cmssw/releases/CMSSW_5_3_24

I updated the twikis.
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe53X
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideMETRecipe
- https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMetAnalysis

I will close this issue.

I will create a new issue for the recipe for CMSSW_7_2_X.
